services:
  - type: web
    name: safecity-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TRTC_APP_ID
        sync: false
      - key: TRTC_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
